services:

  backend:
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - custom_network
    ports:
      - "5000:5000"

  frontend:
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - custom_network
    ports:
      - "4173:4173"
      

      
      
      

networks:
  custom_network:
    driver: bridge
